apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubetest
  labels:
    app: logEcho
spec:
  replicas: 2
  selector:
    matchLabels:
      app: logEcho
  template:
    metadata:
      labels:
        app: logEcho
    spec:
      containers:
      - name: kibana
        image: ngcr.io/kubertest-lcs/kubetest:kibana
        ports:
        - containerPort: 5601
      - name: logstash
        image: ngcr.io/kubertest-lcs/kubetest:logstash
        ports:
        - containerPort: 5000
        - containerPort: 9600
        env:
        - name: "ES_JAVA_OPTS"
          value: "-Xmx256m -Xms256m"
      initContainers:
      - name: elasticsearch
        image: gcr.io/kubertest-lcs/kubetest:elasticsearch
        ports:
        - containerPort: 9200
        - containerPort: 9300
        env:
        - name: "ES_JAVA_OPTS"
          value: "-Xmx256m -Xms256m"
      - name: express
        image: ngcr.io/kubertest-lcs/kubetest:express
        ports:
        - containerPort: 3000
